version: "3"
services:
  akinshinsg-netology-db:
    image: postgres:latest
    container_name: akinshinsg-netology-db
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: akinshin12!3!
      POSTGRES_DB: akinshinsg_db
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      akinshinsg-my-netology-hw:
        ipv4_address: 172.22.0.2
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    links:
      - akinshinsg-netology-db
    container_name: akinshinsg-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: akinshinsg@ilove-netology.com
      PGADMIN_DEFAULT_PASSWORD: akinshin12!3!
    ports:
      - 61231:80
    networks:
      akinshinsg-my-netology-hw:
        ipv4_address: 172.22.0.3
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    links:
      - akinshinsg-netology-db
    container_name: akinshinsg-zabbix-netology
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: akinshin12!3!
    ports:
      - 10051:10051
    networks:
      akinshinsg-my-netology-hw:
        ipv4_address: 172.22.0.4
    restart: always

  zabbix_wgui:
    image: zabbix/zabbix-web-apache-pgsql
    links:
      - akinshinsg-netology-db
      -  pgadmin
      - zabbix-server
    container_name: akinshinsg-netology-zabbix-frontend
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: akinshin12!3!
      ZBX_SERVER_HOST: "zabbix_wgui"
      PHP_TZ: "Europe/Moscow"
    ports:
      - 80:8080
      - 443:8443
    networks:
      akinshinsg-my-netology-hw:
        ipv4_address: 172.22.0.5
    restart: always

networks:
  akinshinsg-my-netology-hw:
    driver: bridge
    ipam:
      config:
      - subnet: 172.22.0.0/24
